MagicVilla_Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;
using AutoMapper;
using MagicVilla_Ultility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using static MagicVilla_Ultility.SD;

namespace MagicVilla_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private readonly IAuthService _authServices;
        private readonly ITokenProvider _tokenProvider;
        private readonly IMapper _mapper;

        public AuthController(ILogger<AuthController> logger, IAuthService authServices, ITokenProvider tokenProvider, IMapper mapper)
        {
            _logger = logger;
            _authServices = authServices;
            _tokenProvider = tokenProvider;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO obj = new LoginRequestDTO();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            var response = await _authServices.LoginAsync<APIResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                var tokenDTO = JsonConvert.DeserializeObject<TokenDTO>(Convert.ToString(response.Result));

                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(tokenDTO.AccessToken);

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == "unique_name").Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));

                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                _tokenProvider.SetToken(tokenDTO);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("CustomeError", response.ErrorMessage.FirstOrDefault());
            return View(obj);
        }

        [HttpGet]
        public IActionResult Register()
        {
            RegisterationRequestDTO obj = new RegisterationRequestDTO(
            )
            {
                // Name="hello from here",
                // UserName ="hi"
            };

            var roleList = new List<SelectListItem>();
            foreach (var role in Enum.GetValues(typeof(Role)))
            {
                roleList.Add(new SelectListItem() { Text = role.ToString(), Value = role.ToString() });
            }
            ViewBag.RoleList = roleList;
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDTO obj)
        {
            obj.Role = obj.Role == null ? Role.User : obj.Role;
            var result = await _authServices.RegisterAsync<APIResponse>(obj);

            if (result != null && result.IsSuccess) return RedirectToAction("login");

            var roleList = new List<SelectListItem>();
            foreach (var role in Enum.GetValues(typeof(Role)))
            {
                roleList.Add(new SelectListItem() { Text = role.ToString(), Value = role.ToString() });
            }
            ViewBag.RoleList = roleList;

            return View(obj);
        }

        public async Task<IActionResult> Logout()
        {
            var token = _tokenProvider.GetToken();
            // set the refresh token chain of specific sesison to false
            await _authServices.LogoutAsync<APIResponse>(token);
            // sign out of from mvc middleware
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using AutoMapper;
using MagicVilla_Ultility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly ILogger<VillaController> _logger;
        private readonly IVillaServices _villaServices;
        private readonly IMapper _mapper;

        public VillaController(ILogger<VillaController> logger, IVillaServices villaServices, IMapper mapper)
        {
            _logger = logger;
            _villaServices = villaServices;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> list = new();
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);

            var response = await _villaServices.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }

            return View(list);

        }
        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
                var response = await _villaServices.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    ViewData["message"] = "Success to create villa";
                    return RedirectToAction(nameof(IndexVilla));
                }
                else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to create villa";
                }
            }
            return View(model);
        }

        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            var response = await _villaServices.GetAsync<APIResponse>(villaId);
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));

                return View(_mapper.Map<VillaUpdateDTO>(model));
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
                var response = await _villaServices.UpdateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["message"] = "Success to update villa";
                    return RedirectToAction(nameof(IndexVilla));
                }
                else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to update villa";
                }
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            if (ModelState.IsValid)
            {
                var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
                var response = await _villaServices.DeleteAsync<APIResponse>(villaId);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
                  else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to delete villa";
                }
            }

            return View();
        }

    }
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MagicVilla_Ultility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Models.VM;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly ILogger<VillaNumberController> _logger;
        private readonly IMapper _mapper;
        private readonly IVillaNumberServices _villaNumberServices;
        private readonly IVillaServices _villaServices;
        public VillaNumberController(ILogger<VillaNumberController> logger, IMapper mapper, IVillaNumberServices villaNumberServices, IVillaServices villaServices)
        {
            _logger = logger;
            _mapper = mapper;
            _villaNumberServices = villaNumberServices;
            _villaServices = villaServices;
        }

        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO>? list = new();
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            var response = await _villaNumberServices.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
            }

            return View(list);

        }

        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new VillaNumberCreateVM();
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            var response = await _villaServices.GetAllAsync<APIResponse>();
            try
            {
                if (response != null && response.IsSuccess)
                {
                    villaNumberVM.VillaList = JsonConvert
                        .DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result))
                        .Select(i => new SelectListItem
                        {
                            Text = i.Name,
                            Value = i.Id.ToString()
                        });
                }
            }
            catch (Exception e)
            {
                villaNumberVM.VillaList = new List<SelectListItem>();
            }

            return View(villaNumberVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            if (ModelState.IsValid)
            {
                var response = await _villaNumberServices.CreateAsync<APIResponse>(model.VillaNumber);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to create villa number";
                }
            }

            // Repopulates the villaList again

            var res = await _villaServices.GetAllAsync<APIResponse>();
            if (res != null && res.IsSuccess)
            {
                model.VillaList = JsonConvert
                    .DeserializeObject<List<VillaDTO>>(Convert.ToString(res.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

            return View(model);
        }

        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> UpdateVillaNumber(int Id)
        {
            var villaNumberVM = new VillaNumberUpdateVM();
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            var response = await _villaNumberServices.GetAsync<APIResponse>(Id);
            if (response == null || response.IsSuccess == false) return NotFound();

            VillaNumberDTO villaNumberDTO = JsonConvert
                .DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
            villaNumberVM.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(villaNumberDTO);


            response = await _villaServices.GetAllAsync<APIResponse>();
            try
            {
                if (response != null && response.IsSuccess)
                {
                    villaNumberVM.VillaList = JsonConvert
                        .DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result))
                        .Select(i => new SelectListItem
                        {
                            Text = i.Name,
                            Value = i.Id.ToString()
                        });
                }
                else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to retrieve villa number";
                }
            }
            catch (Exception e)
            {
                villaNumberVM.VillaList = new List<SelectListItem>();
            }

            return View(villaNumberVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            if (ModelState.IsValid)
            {
                var response = await _villaNumberServices.UpdateAsync<APIResponse>(model.VillaNumber);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                    ? response.ErrorMessage[0]
                    : "Fail to update villa number";
                }
            }

            // Repopulates the villaList again
            var res = await _villaServices.GetAllAsync<APIResponse>();
            if (res != null && res.IsSuccess)
            {
                model.VillaList = JsonConvert
                    .DeserializeObject<List<VillaDTO>>(Convert.ToString(res.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(SD.Role.Admin))]
        public async Task<IActionResult> DeleteVillaNumber(int Id)
        {
            var AccessToken = HttpContext.Session.GetString(SD.AccessToken);
            var response = await _villaNumberServices.DeleteAsync<APIResponse>(Id);


            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            else
            {
                TempData["message"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0)
                ? response.ErrorMessage[0]
                : "Fail to delete villa number";
            }

            return View();
        }


    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@using MagicVilla_Ultility
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class=" nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" type="button" id="dropdownMenuButton1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                @if (User.IsInRole(SD.Role.Admin.ToString()))
                                {
                                    <span>Content Management (Admin role)</span>
                                }
                                else
                                {
                                    <span>Villa and VillaNumber</span>
                                }
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li> <a class="dropdown-item" asp-area="" asp-controller="Villa"
                                        asp-action="IndexVilla">Villa</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="VillaNumber"
                                        asp-action="IndexVillaNumber">VillaNumber</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                            </ul>
                            </;>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div id="myPopup" class="alert alert-primary" style="display: none;">
        
        </div>

        <div class="container">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        window.onload = function () {
        @if (TempData["message"] != null)
        {
            <text>
                setTimeout(function() {
                    var popup =  document.getElementById('myPopup');
                    popup.textContent = '@TempData["message"]';
                    popup.style.display = 'block';

                setTimeout(function() {
                    document.getElementById('myPopup').style.display = 'none';
                        }, 2000); // 3000 milliseconds = 3 seconds
                    }, 0);
            </text>
        }
            }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>